#!/usr/bin/env python
#python 
import sys
import os
from getmagnet import GetFromBTSpread
if len(sys.argv)==1:
    ifpath=input("Please drag file here:");
else:
    ifpath=sys.argv[1];
if not os.path.isfile(ifpath):
    print("please input correct file path to process!");
    input("Press any key");
    os._exit(0);
#Start Phrase Text
print(ifpath);
dfile=open(ifpath,'r');
dlist=[];
for rline in dfile:
    rline=rline.strip('\n');
    dlist[len(dlist):]=rline.split(' ');
dfile.close();
dfile=open(ifpath,'a');
dfile.write("\n\n====Generated by pyHLOL====\n")
totcount=len(dlist);
curcount=0;
for des in dlist:
    curcount+=1;
    if des != '':
         mag=GetFromBTSpread(des);
         dfile.write(mag+'\n');
    print('{0} / {1}'.format(curcount,totcount));
dfile.close();
input("Press any key");
os.system("C:/Windows/System32/notepad.exe "+ifpath);